server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Permite localizar servicios vía Eureka
      routes:
        # Ruta para el servicio de Autenticación (Login)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # Ruta para el servicio de Usuarios (Registro y Perfil)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        # Ruta para el servicio de Cuentas (CVU, Alias, Saldo)
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/